### ISSUE TITLE
Possible workaround for joyent/node#3584, needs testing.

### ISSUE THREAD

**Issue by cowboy** [cowboy/node-exit#1]
An attempt to work around joyent/node#3584.

Anyone interested, give it a test. It's in npm now as `exit@0.1.0`, and I've already tested it (successfully) in OS X 10.8 and Windows 7 on Node.js 0.8.25 and 0.10.18.

/cc @vladikoff @shama @elieux @feklee

**Comment by vladikoff** [comment]
could you update Grunt fork as well? so I can test it. Thanks!

**Comment by cowboy** [comment]
@vladikoff check out the Grunt `exit` branch. Here's the commit: https://github.com/gruntjs/grunt/commit/d5a36bee0209d7dc04609737586ce8f3c9b2affc

**Comment by elieux** [comment]
Works for me. Having to modify the source code is not ideal (especially since the problem wasn't in my project), but it's better than nothing.

**Comment by cowboy** [comment]
Well, if this does, in fact, really work, it can be a nearly drop-in fix for anyone who uses `process.exit`. Let's just start with testing it first and see if there are any issues. After that, start filing PRs on projects :grin:

**Comment by shama** [comment]
I ran `npm test` with Windows 7:
- node v0.8.25
  - `cmd.exe` (4/15 assertions failed)
  - git bash (9/15 assertions failed)
- node v0.10.18
  - `cmd.exe` (4/15 assertions failed)
  - git bash (11/15 assertions failed)

Didn't get a chance to look into why though.

**Comment by cowboy** [comment]
Ok, it would be good to know why. I haven't seen any errors here.

**Comment by shama** [comment]
It seems like it is just the tests being flaky. It appears to work flawlessly in both shells running outside of the tests.

It was failing in git bash because derp, it's bash. So the `find|grep` check based on the platform will try to use `find` which is entirely different command in bash regardless of platform.

With `cmd.exe`, isolating to a single test will give me intermittent failures upon successive runs:

``` shell
C:\Users\Office\Documents\www\node-exit>grunt nodeunit
Running "nodeunit:files" (nodeunit) task
Testing exit_test.js.OK
>> 1 assertions passed (109ms)

Done, without errors.

C:\Users\Office\Documents\www\node-exit>grunt nodeunit
Running "nodeunit:files" (nodeunit) task
Testing exit_test.jsF
>> exit - stdout stderr
>> Message: node log.js 0 10 stdout stderr
>> Error: true == '**UNEXPECTED** [stderr] testing 5\n**UNEXPECTED** [stderr] testing 6\n**EXPECTED** [stderr] testing 5\n**UNEXPECTED** [stderr] testing 7\n**EXPECTED** [stderr] testing 6\n**UNEXPECT
ED** [stderr] testing 8\n**EXPECTED** [stderr] testing 7\n**UNEXPECTED** [stderr] testing 9\n**EXPECTED** [stderr] testing 8\n**EXPECTED** [stderr] testing 9\n'
>> at C:\Users\Office\Documents\www\node-exit\test\exit_test.js:80:14
>> at C:\Users\Office\Documents\www\node-exit\test\exit_test.js:38:5
>> at ChildProcess.exithandler (child_process.js:635:7)
>> at ChildProcess.EventEmitter.emit (events.js:98:17)
>> at maybeClose (child_process.js:735:16)
>> at Socket.<anonymous> (child_process.js:948:11)
>> at Socket.EventEmitter.emit (events.js:95:17)
>> at Pipe.close (net.js:466:12)

Warning: 1/1 assertions failed (187ms) Use --force to continue.

Aborted due to warnings.

C:\Users\Office\Documents\www\node-exit>grunt nodeunit
Running "nodeunit:files" (nodeunit) task
Testing exit_test.js.OK
>> 1 assertions passed (93ms)

Done, without errors.
```

So my guess is jsdiff might be being flaky or something going on there.

Also note all commands are ran with `2>&1 | find "std"`. The `message` of the failing assertions are set to the command before that is appended.

**Comment by cowboy** [comment]
I think this is actually fixed in #2 (yay @vladikoff). This is the best way to test:

(First, make sure that either git and Node.js 0.8.x or 0.10.x are installed)

### The less annoying part
1. clone the repo (or pull if you already have it)
2. cd into the repo's directory
3. `npm install`

### The more annoying part

#### Repeat the following steps with every permutation of:
- Node.js 0.8.x, 0.10.x (ideally the latest versions: 0.8.25, 0.10.18)
- PowerShell, cmd.exe or git-bash
1. run `grunt` (40 assertions should pass)
2. if everything passes, cd into `test/fixtures`
3. run `node log.js 0 10 stdout stderr` and visually inspect it (it should output `stdout 0, stderr 0...stdout 9, stderr 9`, in separate lines, ideally in that order, but **stdout-stderr interleaving order does not matter, only that stdout and stderr are individually in order from 0-9. If you see out-of-orderness, contribute here joyent/node#6249.**
4. ensure the exit code is `0`.
   - in bash, run `echo $?`
   - in cmd.exe, run `echo %ERRORLEVEL%`
   - in PowerShell, run `$lastexitcode`
5. run `node log.js 123 10 stdout stderr` and visually inspect it (see step 3)
6. ensure the exit code is `123` (see step 4)
7. run `node log.js 0 10 stdout stderr 2>&1 | grep "std"` (use `| find "std"` in cmd.exe) and visually inspect it (see step 3)

Here's a screenshot of all three in Node.js 0.10.18.

![WTFMADNESS](http://benalman.com/grab/6d1e58.png)

If only people knew how incredibly painful and time-consuming this is to test. Any help you guys can offer is appreciated.

:heart: :heart: :heart: :heart: :heart:

**Comment by cowboy** [comment]
Also, FWIW I have no idea how to get rid of that weird PowerShell stderr message, but TBH I don't really care about it.

**Comment by bdukes** [comment]
All three shells look good to me on Win 8 & node 0.10.19

**Comment by bdukes** [comment]
And all three shells look good in node 0.8.25

**Comment by nimhawk** [comment]
Run in Win 7 (Enterprise x64 SP1): 

Step 7 in powershell is out of order in the first run and has extra new lines in the output. One all subsequent runs order is correct, but still has the new lines. The rest looks good.

Other shells work exactly as expected.

**Comment by cowboy** [comment]
(I deleted some comments to clean the thread up, including, unfortunately, the one where @nimhawk explained that the extra new lines were cause by him aliasing "grep" to something else)

**Comment by cowboy** [comment]
I'll close this issue and publish 0.1.1 as soon as I get some more confirmations that the current master works per the instructions in [my preceding comment](https://github.com/cowboy/node-exit/issues/1#issuecomment-25087758). /cc @vladikoff @shama

**Comment by nimhawk** [comment]
@cowboy for posterity: I had aliased grep to "select-string" in PowerShell. That's what caused the extra new lines.

**Comment by cowboy** [comment]
Well, I'm going to close this issue as fixed.

Version 0.1.1 is published to npm and pushed to GitHub.

Thanks, everyone, for the help! :heart:
